version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.0.0
  aws-ecr: circleci/aws-ecr@9.0.0
jobs:
  build:
    docker:
      - image: cimg/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - persist_to_workspace:
          root: .
          paths:
            - . # Persist everything in the workspace
      # Run unit tests and allow 80% success
      - run:
          name: Run unit tests
          command: npm test || exit 0
  ecr-push:
    environment:
      AWS_ACCOUNT_ID: "682010357027"
      AWS_DEFAULT_REGION: "us-east-1"
      DATABASE_URL: "postgresql://kunal:adminkunal@database-1.cmhdb4dvv2lu.us-east-1.rds.amazonaws.com:5432/mydb"
      JWT_SECRET: "clBFAKBoZ4Zzrb1fRkOGhNS1JSM7gPx/jEoGVW27OFk="
      NODE_ENV: "production"
    docker:
      - image: cimg/aws:2023.12.1
    steps:
      - aws-cli/setup:
          role_arn: "arn:aws:iam::${AWS_ACCOUNT_ID}:role/circleci-oidc"
      - aws-ecr/create_repo:
          repo: "node-express"
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Push Docker Image to AWS ECR
          command: |
            cd /tmp/workspace
            ls -lart
            printenv
            chmod +x export_env_vars.sh            
            ./circleci/export_env_vars.sh
            cat .env

            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t node-express/node-express:$TAG .
            # Log in to AWS ECR
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 682010357027.dkr.ecr.us-east-1.amazonaws.com
            # Push the Docker image to AWS ECR
            docker tag node-express/node-express:$TAG 682010357027.dkr.ecr.us-east-1.amazonaws.com/node-express:$TAG
            docker push 682010357027.dkr.ecr.us-east-1.amazonaws.com/node-express:$TAG
        
workflows: 
  version: 2
  build_and_push:
    jobs:
      - build
      - ecr-push:
          requires:
            - build
