version: 2.1

jobs:
  checkout_and_test:
    docker:
      - image: circleci/node:lts

    working_directory: ~/repo

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install dependencies
          command: npm install
workflows:
  version: 2
  checkout_and_test:
    jobs:
      - checkout_and_test
