version: 2.1
# orbs:
#   aws-cli: circleci/aws-cli@4.0
#   aws-ecr: circleci/aws-ecr@9.0.4
jobs:
  build:
    docker:
      - image: cimg/node:lts
    # environment:
    #   AWS_REGION: us-east-1
    #   AWS_ACCOUNT_ID: 682010357027
    working_directory: ~/repo
    steps:
      - checkout
      # Install dependencies
      - run:
          name: Install dependencies
          command: npm install
      # Run unit tests and allow 80% success
      - run:
          name: Run unit tests
          command: npm test || exit 0
      # - aws-cli/setup:
      #     role-arn: "arn:aws:iam::${AWS_ACCOUNT_ID}:role/circleci-oidc"
      #     aws-region: "us-east-1"
      # - aws-ecr/ecr_login:
      #     account_id: ${AWS_ACCOUNT_ID}
workflows: 
  version: 2
  build_and_push:
    jobs:
      - build
