version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.0
  aws-ecr: circleci/aws-ecr@9.0.4
jobs:
  checkout_test:
    docker:
      - image: cimg/node:lts
    environment:
      AWS_REGION: us-east-1
      AWS_ACCOUNT_ID: 682010357027
    working_directory: ~/repo
    steps:
      - checkout
      # Install dependencies
      - run:
          name: Install dependencies
          command: npm install
      # Run unit tests and allow 80% success
      - run:
          name: Run unit tests
          command: npm test || exit 0
      - aws-cli/setup:
          role-arn: "arn:aws:iam::${AWS_ACCOUNT_ID}:role/circleci-oidc"
          aws-region: "us-east-1"
      - aws-ecr/ecr_login:
          account_id: ${AWS_ACCOUNT_ID}
      # Build Docker image
      # - setup_remote_docker:
      #     docker_layer_caching: true
      # # build and push Docker image to ECR
      # - run: |
      #     TAG=0.1.$CIRCLE_BUILD_NUM
      #     docker build -t CircleCI-Public/circleci-demo-docker:$TAG .
      #     echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      #     docker push CircleCI-Public/circleci-demo-docker:$TAG
      # - run:
      #     name: Build Docker image
      #     command: |
      #       ls -lart
      #       docker build -t api .
workflows: 
  version: 2
  checkout_test:
    jobs:
      - checkout_test
