version: 2.1

jobs:
  checkout_and_test:
    docker:
      - image: cimg/node:lts

    working_directory: ~/repo

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install dependencies
          command: npm install
      # Run unit tests and allow 80% success
      - run:
          name: Run unit tests
          command: npm test || exit 0
      # Build Docker image
      - run:
          name: Build Docker image
          command: |
            ls -lart
            docker build -t api .
workflows: 
  version: 2
  checkout_and_test:
    jobs:
      - checkout_and_test
