version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.0.0
  aws-ecr: circleci/aws-ecr@9.0.0
  aws-ecs: circleci/aws-ecs@4.0.0
  # snyk: snyk/scan@2.1.0
jobs:
  build:
    docker:
      - image: cimg/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - persist_to_workspace:
          root: .
          paths:
            - . # Persist everything in the workspace
      # Run unit tests and allow 80% success
      - run:
          name: Run unit tests
          command: npm test || exit 0
  ecr-push:
    environment:
      AWS_ACCOUNT_ID: "682010357027"
      AWS_DEFAULT_REGION: "us-east-1"
    docker:
      - image: cimg/aws:2023.12.1
    steps:
      - aws-cli/setup:
          role_arn: "arn:aws:iam::${AWS_ACCOUNT_ID}:role/circleci-oidc"
      - aws-ecr/create_repo:
          repo: "${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}"
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Push Docker Image to AWS ECR
          command: |
            cd /tmp/workspace
            chmod +x .circleci/export_env_vars.sh           
            .circleci/export_env_vars.sh
            cat .env
            TAG=0.1.$CIRCLE_SHA1
            docker build -t ${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}:$TAG .
            # Log in to AWS ECR
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
            # Push the Docker image to AWS ECR
            docker tag ${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}:$TAG ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}:$TAG
            docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}:$TAG
            rm -f .env



workflows:
  build_and_push:
    jobs:
      - build
      - ecr-push:
          requires:
            - build
      - aws-ecs/deploy_service_update:
          requires:
            - ecr-push
          auth:
              - aws-cli/setup:
                  role_arn: "arn:aws:iam::682010357027:role/circleci-oidc"
                  role_session_name: 'ecs-session'
          family: '${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}-service'
          cluster: 'dev-cluster'
          container_image_name_updates: 'container=${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}-container,tag=0.1.${CIRCLE_SHA1}'
          verify_revision_is_deployed: true